[package]
name = "deimos"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5"
toml = "0.5"
dirs = "4"
arboard = "2"
serde = { version= "1", features = ["derive"] }